In [1]:
import numpy as np

In [2]:
# Creating 1-D array
x = np.array([1, 2, 3, 4, 5])
print(x)

# Creating 2-D array
y = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(y)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### How to make float type array?

In [4]:
z = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]], dtype=float)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Initial Placeholder in NUMPY

In [19]:
# creating array of zeros
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# creating array of ones
b = np.ones((3, 3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# creating array of particular values(constant)
c = np.full((3, 3), 7, dtype=float)
print(c)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [21]:
# Create an identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# Create an array with random values
e = np.random.random((3, 3))
print(e)

# create a random integer between 10 to 100
f = np.random.randint(10, 100, size=(3, 3))
print(f)

[[0.54049367 0.806111   0.02397783]
 [0.35319365 0.5933259  0.7490306 ]
 [0.37790697 0.08347652 0.9597757 ]]
[[58 94 70]
 [69 52 24]
 [28 99 73]]


In [34]:
# create an array of evenly spaced values --> specifying the number of values required
g = np.linspace(10, 30, 5)
print(g)

# create an array of evenly spaced values --> specifying the number of steps
h = np.arange(10, 30, 5)
print(h)

[10. 15. 20. 25. 30.]
[10 15 20 25]


### Convert list to numpy array...

In [38]:
my_list = [1, 2, 3, 4, 5]

my_array1 = np.array(my_list)
my_array2 = np.asarray(my_list)

print(type(my_array1))
print(type(my_array2))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Analysing numpy array

In [46]:
x = np.random.randint(1, 10, size=(5, 5))
print(x)

print(f"Array shape : {x.shape}")
print(f"Array Dimension : {x.ndim}")
print(f"Number of element in the array : {x.size}")
print(f"Data type of the array : {x.dtype}")

[[3 5 7 2 9]
 [3 5 3 7 4]
 [2 2 3 9 1]
 [2 6 1 3 2]
 [7 1 2 1 7]]
Array shape : (5, 5)
Array Dimension : 2
Number of element in the array : 25
Data type of the array : int32


### Mathematical Operations

In [58]:
# Let's do addition on the Array
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))

print(f"Array a = \n{a}\n\nArray b = \n{b}")

print(f"\nSum of array a and b = \n{a+b}")
print(f"\nSubtraction of array a and b = \n{a-b}")
print(f"\nMultiplication of array a and b = \n{a*b}")
print(f"\nDivision of array a and b = \n{a/b}")


Array a = 
[[9 1 6]
 [9 6 2]
 [5 8 9]]

Array b = 
[[4 2 9]
 [4 9 8]
 [6 4 6]]

Sum of array a and b = 
[[13  3 15]
 [13 15 10]
 [11 12 15]]

Subtraction of array a and b = 
[[ 5 -1 -3]
 [ 5 -3 -6]
 [-1  4  3]]

Multiplication of array a and b = 
[[36  2 54]
 [36 54 16]
 [30 32 54]]

Division of array a and b = 
[[2.25       0.5        0.66666667]
 [2.25       0.66666667 0.25      ]
 [0.83333333 2.         1.5       ]]


In [60]:
# Other ways for doing array operations
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))

print(f"Array a = \n{a}\n\nArray b = \n{b}")

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))


Array a = 
[[2 8 9]
 [4 3 1]
 [2 4 9]]

Array b = 
[[8 1 9]
 [1 5 3]
 [2 5 2]]
[[10  9 18]
 [ 5  8  4]
 [ 4  9 11]]
[[-6  7  0]
 [ 3 -2 -2]
 [ 0 -1  7]]
[[16  8 81]
 [ 4 15  3]
 [ 4 20 18]]
[[0.25       8.         1.        ]
 [4.         0.6        0.33333333]
 [1.         0.8        4.5       ]]


### Array Manipulation

In [63]:
array = np.random.randint(1, 10, size=(2, 3))
print(array)

# Taking transpose
trans = np.transpose(array)
print(trans)

# Or
print(array.T)


[[8 8 3]
 [9 3 8]]
[[8 9]
 [8 3]
 [3 8]]
[[8 9]
 [8 3]
 [3 8]]


In [64]:
# Reshape the array
array = np.random.randint(1, 10, size=(3, 2))
print(array)

reshape = np.reshape(array, (2, 3))
print(reshape)

[[4 4]
 [1 3]
 [2 7]]
[[4 4 1]
 [3 2 7]]
